apiVersion: v1
kind: Service
metadata:
  name: {{ template "docs.fullname" . }}
  labels:
    {{- include "docs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: default
  selector:
    {{- include "docs.selectorLabels" . | nindent 4 }}
