# Default values for docs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag:
  pullPolicy: Always
docs:
  image:
    tag:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
strategy: Recreate

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: 1
    memory: 250m
  requests:
    cpu: 1
    memory: 100m

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 60
  timeoutSeconds: 60

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 60
  timeoutSeconds: 60

nodeSelector:
  kubernetes.io/os: windows

tolerations: []

affinity: {}
